version: '3.3'

services:
  db:
    image: postgres:13
    restart: always
    volumes:
      - /home/chumba/PycharmProjects/sprint_1_1/data_postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - .env.dev.db
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
  redis:
    image: 'redis:6.2'
    ports:
      - '6379:6379'
